apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: node
  annotations:
    cert-manager.io/inject-ca-from: policies/node-controller
webhooks:
- name: node-controller.policies.svc.cluster.local
  clientConfig:
    service:
      name: node-controller
      namespace: default
      port: 443
      path: /mutate-v1-pods
    caBundle: ""
  failurePolicy: Ignore
  objectSelector:
    matchExpressions:
    - key: app
      operator: NotIn
      values:
      - k8s-policies-controller
  reinvocationPolicy: Never
  rules:
  - resources:
    - pods
    apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
  sideEffects: None
  timeoutSeconds: 5
