version: "3.9"
services:
  builder:
    build: .
    image: builder
    volumes:
    - run:/var/run/docker-entrypoints
    - home:/root:z
    - workspace://workspace:z
    environment:
      TZ:
      REPO_NAME:
      REPO_OWNER:
      GCP_PROJECT:
      GCP_CLUSTER:
      DOCKER_REGISTRY:
      DOCKER_REGISTRY_ORG:
      DOMAIN:
      GIT_BRANCH:
      GIT_USER:
      GIT_PASS:
      GITHUB_USER:
      GITHUB_TOKEN:
    cap_add:
      # For debugging with dlv
      - SYS_PTRACE
    security_opt:
      # For debugging with dlv
      - seccomp:unconfined
volumes:
  workspace:
  home:
  run: