apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: controller-ca
  labels:
    app.kubernetes.io/name: k8s-controller
spec:
  commonName: policies.svc
  isCA: true
  issuerRef:
    name: selfsigned
  secretName: controller-ca
  usages:
  - server auth
  - client auth
