apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: policies/gcpworkload-controller
  labels:
    app.kubernetes.io/instance: gcpworkload
    app.kubernetes.io/name: k8s-policies-controller
  name: gcpworkload
webhooks:
- clientConfig:
    caBundle: ""
    service:
      name: gcpworkload-controller
      namespace: default
      path: /mutate-v1-serviceaccounts
      port: 443
  failurePolicy: Ignore
  name: gcpworkload-controller.policies.svc.cluster.local
  objectSelector:
    matchExpressions:
    - key: app.kubernetes.io/name
      operator: NotIn
      values:
      - k8s-policies-controller
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - DELETE
    resources:
    - serviceaccounts
  sideEffects: NoneOnDryRun
  timeoutSeconds: 5
