apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: policies/node-controller
  labels:
    app.kubernetes.io/instance: node
    app.kubernetes.io/name: k8s-policies-controller
  name: node
webhooks:
- clientConfig:
    caBundle: ""
    service:
      name: node-controller
      namespace: default
      path: /mutate-v1-pods
      port: 443
  failurePolicy: Ignore
  name: node-controller.policies.svc.cluster.local
  objectSelector:
    matchExpressions:
    - key: app.kubernetes.io/name
      operator: NotIn
      values:
      - k8s-policies-controller
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  sideEffects: None
  timeoutSeconds: 5
