apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app.kubernetes.io/component: namespace
    app.kubernetes.io/name: k8s-policies-controller
  name: selfsigned
spec:
  selfSigned: {}
